#:schema node_modules/wrangler/config-schema.json
name = "sublink"
main = "src/index.js"
compatibility_date = "2025-11-14"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "8b024ad8eda245278b306e01f09975ad" }
]
